--[[
  Ordem de arranque canónica (Original Roleplay / Vale do Ipiranga RP).

  Regras desta revisão:
  - Duplicações triviais já consolidadas onde aplicável (`oBillboards` restart tardio).
  - **Mapas cedo**: após `oDestroyer`/`oWater`/`oMapfix`/`oSampModels`, carregar todos os
    recursos com `<map>` no `meta.xml` (conjunto menos exclusions em docs/tooling/rebuild_orp_map_wave.py),
    ordenados alfabéticamente.
  - `oPiruMap` foi substituído por **`oPiruMapOLD`** (recurso presente no pacote).
  - Removidos `oPlant`, `oPlaneCrash`, `gtavbahama` (não existem nesta árvore).
  - Perfis opcionais abaixo — `orpFilterStarterProfile` continua válido (`streamlined` remove dude_* maps).
]]

ORP_ORIGINAL_RP_START_ORDER = {
	"oMysql",
	"oCore",
	"oFont",
	"oCompiler",
	"oDebug",
	"oLogs",
	"oBlur",
	"oBone",
	"oJSON",
	"oPreview",
	"oPreviewNew",
	"oStreamer",
	"oModelLoader",
	"oAnticheat",
	"oAnticheat2",
	"oCustomMarker",
	"oHandling",
	"pmsp",
	"oChat",
	"oSkinProtect",
	"oLoading",
	"o3DElements",
	"oWL",
	"npc_hlc",
	"oDestroyer",
	"oWater",
	"oMapfix",
	"oSampModels",
	"dude_billboard",
	"dude_map",
	"dude_telep",
	"oAlbanian-HQ",
	"oBankMap",
	"oBaysideMap",
	"oBeerMaffiaInterior",
	"oBeerMaffiaInti_map",
	"oBlueberryKikoto",
	"oBorderMap",
	"oBusMap",
	"oBusinessWarhouseMap",
	"oCarrentMap",
	"oCarshop-main",
	"oCartelTijuanaFatelepMap",
	"oCartelTijuanaLatinMap",
	"oCharCreateMap",
	"oCity-Main",
	"oClub-mappolas",
	"oCluckinbellMap",
	"oConstructionMap1",
	"oConstructionMap2",
	"oCrips_HQMap",
	"oDaruparkolo",
	"oDeliMap",
	"oDilimoreGasStationMap",
	"oEastCoastMap",
	"oErtekbecsloMap",
	"oEszakiEpitkezes",
	"oEventMap",
	"oF1mappolas",
	"oFactory",
	"oGanton",
	"oGarageBid_map",
	"oGardenerMap",
	"oGyengelkedo",
	"oHooverMAP",
	"oHospitalInteriorMap",
	"oHospitalLV",
	"oHospitalNewMap",
	"oHospitalNewNewMap",
	"oIdlewoodMap",
	"oIdlewoodMarket",
	"oKinaipiacboltmappolas",
	"oKoltoztetoMap",
	"oKozteruletMap",
	"oKukaMap",
	"oLCMOBMap",
	"oLCMob",
	"oLSFD1",
	"oLSFD2",
	"oLezarasok",
	"oLosZetasMap",
	"oMechanicLV",
	"oMechanicMap",
	"oMechanicMap_OLD_OLD",
	"oMexikoHQ",
	"oNAV",
	"oNAVInterior",
	"oNewCityhallMap",
	"oNewDeliMap",
	"oNewPD",
	"oNewSzereloMap",
	"oPDInteriorMap",
	"oPDLefoglaltMap",
	"oPDOutsideMap",
	"oPD_TrainingMap",
	"oParkolo",
	"oPatrikbirtok",
	"oPiruMapOLD",
	"oPlazaConstruction",
	"oPlazaMap",
	"oPoliceCellsInterior_MAP",
	"oRally-Map",
	"oSormaffiaMap",
	"oTakaritoNew",
	"oTuningLV",
	"oTuningMap",
	"oUC_map_blueberry",
	"oUC_map_eastls",
	"oUjsagos_map",
	"oVH-LV",
	"oVelvettFKMap",
	"oVhMap",
	"oWahChing",
	"oWellStackedMap",
	"oZacskosBirtok",
	"trailerDepoBuild",
	"oUjsag",
	"oFurnitures",
	"oUjszerelo",
	"oHospitalTexture",
	"oHooverHQfix",
	"oInfobox",
	"oRadar",
	"oSpeedo",
	"oNametag",
	"oInventory",
	"oInterface",
	"oHud",
	"oCrosshair",
	"oNoblur",
	"oDeath",
	"oAccount",
	"oVehicle",
	"oCarshop",
	"oNewSkinshop",
	"oInteriors",
	"oAdmin",
	"oAnims",
	"oDashboard",
	"oScoreboard",
	"oTips",
	"oJob",
	"oLicenses",
	"oCVEH",
	"oLvl",
	"oBus",
	"oShop",
	"oElementEditor",
	"oGate",
	"oIndex",
	"oTraffipax",
	"oJob_Newspaper",
	"oJob_Cleaner",
	"oJob_PizzaMaker",
	"oJob_FurnitureTransport",
	"oPlacedo",
	"oHifi",
	"oCasino",
	"oTuning",
	"oQuitmessage",
	"oFactionScripts",
	"oWanted",
	"oTerritory",
	"oFactionHQ",
	"oInteraction",
	"oBoneDamage",
	"oFishing",
	"oPhone",
	"oMarket",
	"oBank",
	"oPayday",
	"oSiren",
	"oWeaponModels",
	"oPaintjobs",
	"oBetterRain",
	"oWeaponSkill",
	"oPayNSpray",
	"oJunkyard",
	"oDrugs",
	"oMinigames",
	"oBankrob",
	"oVehicleRadio",
	"oJob_Cashier",
	"oJob_Hacker",
	"oTempomat",
	"oForestAnimals",
	"oMDC",
	"oFuel",
	"oTBoards",
	"oTeslaCharger",
	"oWeaponShop",
	"oDriveschool",
	"oVehicleExtras",
	"oTreasureHunt",
	"oExtraCommands",
	"oGNIproperty",
	"oPremium",
	"oBag",
	"oVehicleFixMarker",
	"oJob_Gardener",
	"oWeaponSkins",
	"oTeslaDriveAssist",
	"oDx",
	"oPrinter",
	"oRope",
	"oTicket",
	"oRoulette",
	"oMushrooms",
	"oWeaponCraft",
	"oGarageBid",
	"oBillboards",
	"oPet",
	"oDevtools",
	"oShark",
	"oInteriorBuilding",
	"oJob_Crane",
	"oGoggle",
	"cigy",
	"oGraffiti",
	"oNAVSkins",
	"oShaders",
	"oShader_Water",
	"oShader_Bloom",
	"oShader_Depth",
	"oShader_HDTextures",
	"oShader_VehicleReflection",
	"oShader_Palette",
	"oShader_MotionBlur",
	"oShader_Vignette",
	"oShader_Snow",
	"oShader_FXAA",
	"serialcheck",
}

--- Recursos “opcionais” removidos no perfil `streamlined` (mapas/eventos periféricos e verificações não críticas).
ORP_STREAMLINED_EXCLUDE = {
	dude_telep = true,
	dude_map = true,
	dude_billboard = true,
	cigy = true,
	oShark = true,
	serialcheck = true,
}

function orpFilterStarterProfile(profileName, orderedList)
	local name = profileName or "original_rp"
	if name == "streamlined" then
		local filtered = {}
		for _, rw in ipairs(orderedList) do
			if not ORP_STREAMLINED_EXCLUDE[rw] then
				filtered[#filtered + 1] = rw
			end
		end
		return filtered
	end
	return orderedList
end
